title: '400 Golden Gate Point #22'
swipe_nav:
  wrap: true
  animate: swipe
  prevent_default: true
views:
  - title: Main
    path: main
    icon: mdi:sofa
    theme: Mushroom
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: custom:layout-card
            layout_type: custom:grid-layout
            layout:
              grid-template-columns: 80% 20%
              grid-template-rows: auto
              justify-content: left
              gap: 10px
            card_mod: |
              style: |
                div {
                      --state-icon-active-color: rgb(9, 251, 213);
                      --paper-item-icon-active-color: var(--state-icon-active-color);
                      --state-icon-color: rgb(50,50,255);
                      --paper-item-icon-color: var(--paper-item-icon-color);
                    }  
            cards:
              - type: vertical-stack
                cards:
                  - type: custom:simple-thermostat
                    entity: climate.ecobee
                    decimals: '0'
                    header: true
                    control: true
                    layout:
                      step: column
                      sensors:
                        type: table
                    sensors:
                      - entity: sensor.ecobee_bedroom_temperature
                        name: Bedroom
                        decimals: 0
                    step_size: '1'
                    hide:
                      state: true
                    style: |
                      ha-card {
                        --st-font-size-xl: 24px;
                        --st-font-size-m: 20px;
                        --st-font-size-title: 0px;
                        --st-font-size-sensors: 14px;
                        --st-spacing: 2px;
                        --heat_cool-color: green;
                      }
                    card_mod:
                      style: |
                        .mode-title { display: none}
                        h3.current--value {
                          background-color: hsl(0deg,70%,30%);
                          border-radius: 9999px;
                          display: block;
                          color: white;
                          padding: 14px;
                          width: 60%;
                          height: 50%;
                          font-size: 24px;
                          position: relative;
                        }
                        .current-wrapper:last-child h3.current--value {
                          background-color: hsl(250deg,70%,30%) !important;
                        }  
                        .active.heat_cool {
                          background-color: green !important;} 


                        .current--value.updating {
                          background-color: #4444;
                          color: #ffffff;
                        }
                        .current--value.updating:after {
                          content: 'updating';
                          position: absolute;
                          top: 60px;
                          left: 0px;
                          right: 0px;
                          opacity: 0.7;
                          font-size: 14px;
                          border-radius: 99999px;
                          background-color: white;
                          color: black;
                          text-align: center;
                        }
                    view_layout:
                      grid-column: 1/1

#fans
                  - type: custom:mushroom-fan-card
                    entity: switch.pulley_fan_switch_1
                    name: Pulley Fan
                    icon_animation: false
                    fill_container: true
                    layout: vertical
                    icon_type: icon
                    icon: mdi:fan-plus
                    view_layout:
                      grid-area: fp
                  - type: custom:mushroom-fan-card
                    entity: switch.lanai_fan_switch_1
                    name: Lanai Fan
                    icon_animation: false
                    fill_container: true
                    layout: vertical
                    icon_type: icon
                    icon: mdi:fan
                    view_layout:
                      grid-area: fl
#lights
                  - type: custom:mushroom-light-card
                    entity: light.kitchen_light
                    name: Kitchen
                    layout: horizontal
                    fill_container: false
                    use_light_color: true
                    show_brightness_control: true
                    show_color_temp_control: false
                    show_color_control: false
                    collapsible_controls: false

                  - type: custom:mushroom-light-card
                    entity: light.living_room_light
                    name: Living Room
                    layout: horizontal
                    fill_container: false
                    use_light_color: true
                    show_brightness_control: true
                    show_color_temp_control: false
                    show_color_control: false
                    collapsible_controls: false
                    
                  - type: custom:mushroom-light-card
                    entity: light.dining_light
                    name: Dining
                    layout: horizontal
                    fill_container: false
                    use_light_color: true
                    show_brightness_control: true
                    show_color_temp_control: false
                    show_color_control: false
                    collapsible_controls: false

                    
                  - type: custom:mushroom-light-card
                    entity: light.hall_light_light
                    name: Hall
                    layout: horizontal
                    fill_container: false
                    use_light_color: true
                    show_brightness_control: true
                    show_color_temp_control: false
                    show_color_control: false
                    collapsible_controls: false
 
                  - type: custom:mushroom-light-card
                    entity: switch.plug_3
                    name: Floor Lamp
                    icon: mdi:light-flood-down

# windows
                  - type: custom:mushroom-cover-card
                    entity: cover.kitchen_window
                    name: Kitchen
                    fill_container: true
                    layout: vertical
                    show_position_control: true
                    show_buttons_control: true

                  - type: custom:mushroom-cover-card
                    entity: cover.living_room_window
                    name: Living Room
                    fill_container: true
                    layout: vertical
                    show_position_control: true
                    show_buttons_control: true                    

#other
                  - type: custom:mushroom-lock-card
                    entity: lock.front_door
                    fill_container: true
                    layout: vertical
                    primary_info: name
                    secondary_info: state
                    icon_type: none
                    view_layout:
                      grid-area: lfd
                  - type: custom:mushroom-entity-card
                    entity: water_heater.snvr104582q_oven
                    layout: vertical
                    fill_container: true
                    tap_action:
                      action: more-info
                    name: Oven
#bedroom                    
  - title: Bedrooms
    path: bedrooms
    icon: mdi:bed
    theme: Mushroom
    panel: true
    badges: []
    cards:
      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 80% 20%
          grid-template-rows: auto
          justify-content: left
          gap: 10px
        cards:
          - type: vertical-stack
            cards:
#fans
              - type: entities
                entities:
                  - entity: sensor.ecobee_bedroom_temperature
                    name: Bedroom Temperature
                  - entity: fan.master_fan
                  - entity: light.master_fan
         
#lights
              - type: custom:mushroom-light-card
                entity: light.master_ceiling_lights
                name: Master Ceiling
                layout: vertical
                fill_container: false
                use_light_color: true
                show_brightness_control: true
                show_color_temp_control: false
                show_color_control: false
                collapsible_controls: false
              
              - type: custom:mushroom-light-card
                entity: light.freds_bed_lamp
                name: Fred's Lamp
                layout: vertical
                icon: mdi:lightbulb
                view_layout:
                  grid-area: fl
                fill_container: true
                use_light_color: true
                show_brightness_control: true
                show_color_temp_control: true
                show_color_control: true
                collapsible_controls: false
#windows
              - type: custom:mushroom-cover-card
                entity: cover.master_shade
                name: Master Window
                fill_container: true
                layout: vertical
                show_position_control: true
                show_buttons_control: true
              - type: custom:mushroom-cover-card
                entity: cover.master_slider
                name: Master Slider
                fill_container: true
                layout: vertical
                show_position_control: true
                show_buttons_control: true


  - title: Camera
    icon: mdi:camera
    cards:
      - type: picture-elements
        entity: camera.door_camera
        camera_image: camera.door_camera
        camera_view: live
        elements:
          - type: icon
            icon: mdi:arrow-up
            style:
              background: rgba(255, 255, 255, 0.25)
              right: 25px
              bottom: 50px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: up
          - type: icon
            icon: mdi:arrow-down
            style:
              background: rgba(255, 255, 255, 0.25)
              right: 25px
              bottom: 0px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: down
          - type: icon
            icon: mdi:arrow-left
            style:
              background: rgba(255, 255, 255, 0.25)
              right: 50px
              bottom: 25px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: left
          - type: icon
            icon: mdi:arrow-right
            style:
              background: rgba(255, 255, 255, 0.25)
              right: 0px
              bottom: 25px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: right
          - type: icon
            icon: mdi:arrow-top-left
            style:
              background: rgba(255, 255, 255, 0.25)
              right: 50px
              bottom: 50px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: left_up
          - type: icon
            icon: mdi:arrow-top-right
            style:
              background: rgba(255, 255, 255, 0.25)
              right: 0px
              bottom: 50px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: right_up
          - type: icon
            icon: mdi:arrow-bottom-left
            style:
              background: rgba(255, 255, 255, 0.25)
              right: 50px
              bottom: 0px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: left_down
          - type: icon
            icon: mdi:arrow-bottom-right
            style:
              background: rgba(255, 255, 255, 0.25)
              right: 0px
              bottom: 0px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: right_down
          - type: icon
            icon: mdi:magnify
            style:
              background: rgba(255, 255, 255, 0.25)
              bottom: 25px
              right: 25px
            tap_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: zoom_in
            hold_action:
              action: call-service
              service: amcrest.ptz_control
              service_data:
                entity_id: camera.door_camera
                movement: zoom_out
      - type: entities
        entities:
          - entity: binary_sensor.door_camera_audio_detected
          - entity: binary_sensor.door_camera_motion_detected
          - entity: sensor.door_camera_sd_used
          - entity: binary_sensor.front_door_closed
  - title: LEDs
    path: leds
    icon: mdi:dots-horizontal-circle-outline
    type: panel
    badges: []
    cards:
      - type: iframe
        style: |
          ha-card {box-shadow: 0 0 }
        url: https://22.400ggp.com/local/html/leds.html?i=11
