title: '400 Golden Gate Point #22'
swipe_nav:
  wrap: true
  animate: swipe
  prevent_default: true
views:
  - title: Main
    path: main
    icon: mdi:sofa
    theme: Caule Black Green Glass
    badges: []
    cards:
      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 50% 50%
          grid-template-rows: auto
        cards:
          - type: custom:slider-button-card
            entity: light.kitchen
            name: Kitchen
            style: |
              ha-card { --state-color-off: #aaaaaa; 
                        --paper-item-icon-color: #aaaaaa;
                      }
            slider:
              direction: left-right
              background: gradient
              use_percentage_bg_opacity: true
              use_state_color: false
              show_track: true
              force_square: false
            action_button:
              mode: toggle
            icon:
              icon: hass:lightbulb
              show: true
              use_state_color: true
            compact: true
            view_layout: column:1
          - type: custom:slider-button-card
            entity: light.living_room
            style: |
              ha-card { --state-color-off: #aaaaaa; 
                        --paper-item-icon-color: #aaaaaa;
                      }
            slider:
              direction: left-right
              background: gradient
              use_percentage_bg_opacity: true
              use_state_color: false
              show_track: true
              force_square: false
            action_button:
              mode: toggle
            icon:
              icon: ''
              show: true
              use_state_color: true
            compact: true
            view_layout:
              column: 2
          - type: custom:slider-button-card
            entity: light.dining
            style: |
              ha-card { --state-color-off: #aaaaaa; 
                        --paper-item-icon-color: #aaaaaa
                      }
            slider:
              direction: left-right
              background: gradient
              use_percentage_bg_opacity: true
              use_state_color: false
              show_track: true
              force_square: false
            action_button:
              mode: toggle
            icon:
              icon: ''
              show: true
              use_state_color: true
            compact: true
          - type: custom:slider-button-card
            entity: light.hall
            style: |
              ha-card { --state-color-off: #aaaaaa; 
                        --paper-item-icon-color: #aaaaaa
                      }
            slider:
              direction: left-right
              background: gradient
              use_percentage_bg_opacity: true
              use_state_color: false
              show_track: true
              force_square: false
            action_button:
              mode: toggle
            icon:
              icon: ''
              show: true
              use_state_color: true
            compact: true
          - type: custom:slider-button-card
            entity: cover.kitchen
            style: |
              ha-card { --state-color-off: #aaaaaa; 
                        --paper-item-icon-color: #aaaaaa
                      }
            slider:
              direction: top-bottom
              background: striped
              use_state_color: false
              use_percentage_bg_opacity: false
              toggle_on_click: false
              show_track: false
              force_square: false
              invert: true
            action_button:
              mode: toggle
            icon:
              icon: ''
              show: true
              use_state_color: true
            compact: true
          - type: custom:slider-button-card
            entity: cover.living_room
            style: |
              ha-card { --state-color-off: #aaaaaa; 
                        --paper-item-icon-color: #aaaaaa
                      }
            slider:
              direction: top-bottom
              background: striped
              use_state_color: false
              use_percentage_bg_opacity: false
              toggle_on_click: false
              show_track: false
              force_square: false
              invert: true
            action_button:
              mode: toggle
            icon:
              icon: ''
              show: true
              use_state_color: true
            compact: true
          - type: custom:slider-button-card
            entity: switch.pulley_fan
            name: Pulley Fan
            slider:
              direction: bottom-top
              background: solid
              use_percentage_bg_opacity: false
              use_state_color: false
              show_track: true
              force_square: false
              toggle_on_click: true
            action_button:
              mode: toggle
              show: true
            icon:
              icon: hass:fan
              show: true
              use_state_color: false
            compact: true
          - type: custom:slider-button-card
            entity: switch.lanai_fan
            name: Lanai Fan
            slider:
              direction: bottom-top
              background: solid
              use_percentage_bg_opacity: false
              use_state_color: false
              show_track: true
              force_square: false
              toggle_on_click: true
            action_button:
              mode: toggle
              show: true
            icon:
              icon: hass:fan
              show: true
              use_state_color: false
            compact: true
          - type: thermostat
            entity: climate.ecobee
            name: ' '
            view_layout:
              grid-column: 1/3
  - title: Bedrooms
    path: bedrooms
    icon: mdi:bed
    theme: Caule Black Gray Glass
    type: custom:horizontal-layout
    layout:
      max_cols: 10
    badges: []
    cards: []
  - path: all_devices
    title: All Devices
    badges: []
    cards:
      - type: entities
        entities:
          - sensor.openweathermap_weather
          - sensor.openweathermap_dew_point
          - sensor.openweathermap_temperature
          - sensor.openweathermap_feels_like_temperature
          - sensor.openweathermap_wind_speed
          - sensor.openweathermap_wind_bearing
          - sensor.openweathermap_humidity
          - sensor.openweathermap_pressure
          - sensor.openweathermap_cloud_coverage
          - sensor.openweathermap_rain
          - sensor.openweathermap_snow
          - sensor.openweathermap_precipitation_kind
          - sensor.openweathermap_uv_index
          - sensor.openweathermap_condition
          - sensor.openweathermap_weather_code
          - sensor.openweathermap_forecast_condition
          - sensor.openweathermap_forecast_precipitation
          - sensor.openweathermap_forecast_precipitation_probability
          - sensor.openweathermap_forecast_pressure
          - sensor.openweathermap_forecast_temperature
          - sensor.openweathermap_forecast_temperature_low
          - sensor.openweathermap_forecast_time
          - sensor.openweathermap_forecast_wind_bearing
          - sensor.openweathermap_forecast_wind_speed
          - sensor.openweathermap_forecast_cloud_coverage
        title: 400GGP
      - type: entities
        entities:
          - sensor.samsung_q60_volume
          - sensor.samsung_q60_media_playback_status
          - sensor.samsung_q60_tv_channel
          - sensor.samsung_q60_tv_channel_name
          - switch.samsung_q60
          - binary_sensor.ecobee_bedroom_occupancy
          - sensor.ecobee_bedroom_temperature
          - cover.master_window
          - cover.master_slider
          - sensor.master_window_signal
          - sensor.master_slider_signal
        title: Bedroom
      - type: entities
        entities:
          - cover.guest_slider
          - sensor.guest_slider_signal
        title: Guest room
      - type: entities
        entities:
          - lock.front_door
        title: Hall
      - type: entities
        entities:
          - cover.kitchen
          - entity: sensor.kitchen_signal
            name: Signal
          - binary_sensor.snvr104582q_remote_enabled
          - sensor.snvr104582q_cook_mode
          - sensor.snvr104582q_cook_time_remaining
          - sensor.snvr104582q_kitchen_timer
          - sensor.snvr104582q_user_temp_offset
          - sensor.snvr104582q_raw_temperature
          - switch.snvr104582q_sabbath_mode
          - water_heater.snvr104582q_oven
        title: Kitchen
      - type: entities
        entities:
          - entity: switch.lanai_fan
            name: Fan
        title: Lanai
      - type: entities
        entities:
          - sensor.ecobee_humidity
          - binary_sensor.ecobee_occupancy
          - sensor.ecobee_temperature
          - cover.living_room
          - entity: sensor.living_room_signal
            name: Signal
          - sensor.my_wall_panel_light
          - binary_sensor.my_wall_panel_usb_plugged
          - binary_sensor.my_wall_panel_ac_plugged
          - binary_sensor.my_wall_panel_charging
          - binary_sensor.my_wall_panel_motion_detected
        title: Living Room
      - type: thermostat
        entity: climate.ecobee
      - type: weather-forecast
        entity: weather.ecobee
        show_forecast: false
      - type: entities
        entities:
          - binary_sensor.door_camera_audio_detected
          - binary_sensor.door_camera_motion_detected
          - binary_sensor.door_camera_online
          - binary_sensor.front_door_closed
          - binary_sensor.updater
        title: Binary sensor
      - type: picture-entity
        entity: camera.door_camera
      - type: entities
        entities:
          - fan.eb62af8a93acc91276vbf7
        title: Fan
      - type: entities
        entities:
          - input_boolean.front_door_sensor
        title: Input boolean
      - type: entities
        entities:
          - light.master_lamp
          - light.kitchen
          - light.dining
          - light.hall
          - light.living_room
          - light.master_ceiling
        title: Light
      - type: entities
        entities:
          - person.fred
        title: Person
      - type: entities
        entities:
          - scene.evening
        title: Scene
      - type: entities
        entities:
          - sensor.disk_use_percent_config
          - sensor.disk_use_percent_dev_root
          - sensor.disk_use_percent_home
          - sensor.door_camera_ptz_preset
          - sensor.door_camera_sd_used
          - sensor.load_15m
          - sensor.load_1m
          - sensor.load_5m
          - sensor.memory_free
          - sensor.memory_use_percent
          - sensor.processor_temperature
          - sensor.processor_use_percent
          - sensor.hacs
        title: Sensor
      - type: entities
        entities:
          - sun.sun
        title: Sun
      - type: entities
        entities:
          - switch.wyze_notifications
          - switch.wyze_notifications_off
          - switch.wyze_notifications_off_2
          - switch.wyze_notifications_off_3
          - switch.wyze_notifications_off_4
          - switch.wyze_notifications_off_5
          - switch.wyze_notifications_off_6
          - switch.wyze_notifications_off_7
          - switch.wyze_notifications_off_8
          - switch.wyze_notifications_off_9
          - switch.wyze_notifications_off_10
          - switch.wyze_notifications_off_11
          - switch.wyze_notifications_off_12
          - switch.wyze_notifications_off_13
          - switch.wyze_notifications_off_14
          - switch.wyze_notifications_off_15
          - switch.wyze_notifications_off_16
          - switch.wyze_notifications_off_17
          - switch.wyze_notifications_on
          - switch.wyze_notifications_on_2
          - switch.wyze_notifications_on_3
          - switch.wyze_notifications_on_4
          - switch.wyze_notifications_on_5
          - switch.wyze_notifications_on_6
          - switch.wyze_notifications_on_7
          - switch.wyze_notifications_on_8
          - switch.wyze_notifications_on_9
          - switch.wyze_notifications_on_10
          - switch.wyze_notifications_on_11
          - switch.wyze_notifications_on_12
          - switch.wyze_notifications_on_13
          - switch.wyze_notifications_on_14
          - switch.wyze_notifications_on_15
          - switch.wyze_notifications_on_16
          - switch.wyze_notifications_on_17
          - switch.pulley_fan
        title: Switch
      - type: weather-forecast
        entity: weather.home
        show_forecast: false
      - type: weather-forecast
        entity: weather.openweathermap
        show_forecast: false
  - type: custom:horizontal-layout
    layout:
      column: 2
    badges: []
    cards: []
